name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: yarn publish
