name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libavahi-compat-libdnssd-dev
          sudo apt-get install wine64
          sudo apt-get install wine32
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: yarn run publish
      - if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: yarn run publish --platform=win32
